### ISSUE TITLE
[Bug]: mc.runcmd("backup") 出现报错，无法正常进行存档热备份 ERROR [Server] Unknown operation

### ISSUE THREAD

**Issue by yufengya0420** [ShrBox/BackupHelper#3]
### Describe the bug

![image](https://github.com/ShrBox/BackupHelper/assets/99462074/acdb2fd1-b378-4fea-b929-9fdd59283991)

控制台执行mc.runcmd("backup")指令出现报错，无法正常进行存档热备份

### To Reproduce

控制台执行mc.runcmd("backup")

### Expected behavior

正常进行存档热备份

### Screenshots

![image](https://github.com/ShrBox/BackupHelper/assets/99462074/f44315af-0eb1-4cbd-89d1-5127f8744754)

### Platform

Win10

### BDS Version

1.20.80

### LeviLamina Version

0.12.1

### Version

0.4.1

**Comment by yufengya0420** [comment]
![image](https://github.com/ShrBox/BackupHelper/assets/99462074/4add047d-1c73-4cd1-a510-bdc33c185f18)

**Comment by ShrBox** [comment]
无法复现，我使用的LSE版本是0.7.2

**Comment by yufengya0420** [comment]
> 无法复现，我使用的LSE版本是0.7.2

![image](https://github.com/ShrBox/BackupHelper/assets/99462074/fcf9eb2d-4e2a-4ed5-9cd4-db52283f7c51)

我也是0.7.2，我再测测

**Comment by yufengya0420** [comment]
> 无法复现，我使用的LSE版本是0.7.2

你试试 jsdebug mc.runcmdEx("backup") 看看输出什么

**Comment by yufengya0420** [comment]
> 无法复现，我使用的LSE版本是0.7.2

![image](https://github.com/ShrBox/BackupHelper/assets/99462074/b6742fc8-9f6d-47de-a75e-8947de9524de)

我设置的整点备份，发现是概率性报错

**Comment by yufengya0420** [comment]
> > 无法复现，我使用的LSE版本是0.7.2
> 
> ![image](https://private-user-images.githubusercontent.com/99462074/326557520-b6742fc8-9f6d-47de-a75e-8947de9524de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTgxMDEsIm5iZiI6MTcxNDQxNzgwMSwicGF0aCI6Ii85OTQ2MjA3NC8zMjY1NTc1MjAtYjY3NDJmYzgtOWY2ZC00N2RlLWE3NWUtODk0N2RlOTUyNGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE5MTAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4ZWYxNDcwN2EzNjYzN2FkZWYyNWViYTI0NWI4OTkzYTRhNDk2NGYzYmY0MDUzOTcxM2QyMTFmZDY5OWUyNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TmIf-LL36Oy7pp9-Ste2IT_w143KH8JWRkR5hXPDEmw)
> 
> 我设置的整点备份，发现是概率性报错

两点的时候报错，三点的时候又成功备份了，不知道啥情况

**Comment by yufengya0420** [comment]
![image](https://github.com/ShrBox/BackupHelper/assets/99462074/6970e6db-458f-4889-82bc-d4ee918673c4)

有的时候报错但是又执行成功了，奇怪了
